apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testdc4456
spec:
  metrics:
    - name: testdc4456
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://isd-argocd.isd-dev.opsmx.net/
          user: user2
          application: testdc3
          baselineStartTime: "2022-10-26T13:00:00Z"
          canaryStartTime: "2022-10-26T13:00:00Z"
          lifetimeMinutes: 30
          gitops: true
          threshold: 
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: metrictemplatemissingfields
            metricScopeVariables: "job_name"
            baselineMetricScope: "baseline-redis"
            canaryMetricScope: "baseline-redis"
